language: java
env:
  - CODECOV_TOKEN="c74bdf1d-bbd5-4b15-aff0-06185b43ccb1"
script:
  - cd proxy-server
  - mvn clean package
  - bash <(curl -s https://codecov.io/bash)
  - cd ../prime-number-server
  - mvn clean package
  - bash <(curl -s https://codecov.io/bash)

